-- MySQL Script generated by MySQL Workbench
-- Mon Apr  4 13:12:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema integradora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema integradora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `integradora` DEFAULT CHARACTER SET utf8 ;
USE `integradora` ;

-- -----------------------------------------------------
-- Table `integradora`.`horarioVentanilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`horarioVentanilla` (
  `idHorarioVentanilla` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  `repeticiones` INT NOT NULL,
  `numVentanilla` INT NOT NULL,
  PRIMARY KEY (`idHorarioVentanilla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integradora`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`servicio` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `documentosRequeridos` VARCHAR(100) NOT NULL,
  `costo` DECIMAL(5,3) NOT NULL,
  PRIMARY KEY (`idServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integradora`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integradora`.`solicitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`solicitante` (
  `matricula` VARCHAR(20) NOT NULL,
  `carrera` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `FK_usuario_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `FK_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `integradora`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integradora`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`cita` (
  `idcita` INT NOT NULL AUTO_INCREMENT,
  `hora` TIME NOT NULL,
  `ventanilla` INT NOT NULL,
  `servicioSolicitado` INT NOT NULL,
  `documentosAnexos` VARCHAR(255) NULL,
  `pago` TINYINT(1) NOT NULL,
  `solicitante` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idcita`),
  INDEX `FK_horario_idx` (`ventanilla` ASC) VISIBLE,
  INDEX `FK_servicios_idx` (`servicioSolicitado` ASC) VISIBLE,
  INDEX `FK_solicitante_idx` (`solicitante` ASC) VISIBLE,
  CONSTRAINT `FK_horario`
    FOREIGN KEY (`ventanilla`)
    REFERENCES `integradora`.`horarioVentanilla` (`idHorarioVentanilla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_servicios`
    FOREIGN KEY (`servicioSolicitado`)
    REFERENCES `integradora`.`servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_solicitante`
    FOREIGN KEY (`solicitante`)
    REFERENCES `integradora`.`solicitante` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integradora`.`tipoDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`tipoDocumento` (
  `idTipoDocumento` INT NOT NULL,
  PRIMARY KEY (`idTipoDocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integradora`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `authority` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integradora`.`userRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`userRole` (
  `idUserRole` INT NOT NULL,
  `role` INT NOT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`idUserRole`),
  INDEX `FK_User_idx` (`user` ASC) VISIBLE,
  INDEX `FK_Role_idx` (`role` ASC) VISIBLE,
  CONSTRAINT `FK_User`
    FOREIGN KEY (`user`)
    REFERENCES `integradora`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Role`
    FOREIGN KEY (`role`)
    REFERENCES `integradora`.`role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
